import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1773848984831 implements MigrationInterface {
    name = 'InitialSchema1773848984831'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`addresses\` (\`id\` VARCHAR(36) NOT NULL, \`userId\` varchar(255) NOT NULL, \`fullName\` varchar(255) NOT NULL, \`phone\` varchar(20) NOT NULL, \`street\` varchar(500) NOT NULL, \`city\` varchar(100) NOT NULL, \`district\` varchar(100) NOT NULL, \`ward\` varchar(100) NOT NULL, \`isDefault\` tinyint NOT NULL DEFAULT 0, \`type\` enum ('shipping', 'billing') NOT NULL DEFAULT 'shipping', \`latitude\` decimal(10,7) NULL, \`longitude\` decimal(10,7) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_95c93a584de49f0b0e13f75363\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`categories\` (\`id\` VARCHAR(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`slug\` varchar(255) NOT NULL, \`description\` text NULL, \`parentId\` varchar(255) NULL, \`image\` varchar(500) NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`displayOrder\` int NOT NULL DEFAULT '0', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_420d9f679d41281f282f5bc7d0\` (\`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`brands\` (\`id\` VARCHAR(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`slug\` varchar(255) NOT NULL, \`logo\` varchar(500) NULL, \`description\` text NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_b15428f362be2200922952dc26\` (\`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`product_images\` (\`id\` VARCHAR(36) NOT NULL, \`productId\` varchar(255) NOT NULL, \`url\` varchar(500) NOT NULL, \`publicId\` varchar(255) NULL, \`altText\` varchar(255) NULL, \`displayOrder\` int NOT NULL DEFAULT '0', \`isPrimary\` tinyint NOT NULL DEFAULT 0, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_b367708bf720c8dd62fc683316\` (\`productId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`carts\` (\`id\` VARCHAR(36) NOT NULL, \`userId\` varchar(255) NULL, \`sessionId\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_69828a178f152f157dcf2f70a8\` (\`userId\`), UNIQUE INDEX \`IDX_08c5fb75dc0c2ed434aac2b0f5\` (\`sessionId\`), UNIQUE INDEX \`REL_69828a178f152f157dcf2f70a8\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cart_items\` (\`id\` VARCHAR(36) NOT NULL, \`cartId\` varchar(255) NOT NULL, \`productId\` varchar(255) NOT NULL, \`variantId\` varchar(255) NULL, \`quantity\` int NOT NULL, \`price\` decimal(15,2) NOT NULL, \`addedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_edd714311619a5ad0952504583\` (\`cartId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`product_variants\` (\`id\` VARCHAR(36) NOT NULL, \`productId\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, \`sku\` varchar(100) NOT NULL, \`price\` decimal(15,2) NOT NULL, \`quantity\` int NOT NULL DEFAULT '0', \`attributes\` json NULL, \`image\` varchar(500) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_f515690c571a03400a9876600b\` (\`productId\`), UNIQUE INDEX \`IDX_46f236f21640f9da218a063a86\` (\`sku\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`review_replies\` (\`id\` VARCHAR(36) NOT NULL, \`reviewId\` varchar(255) NOT NULL, \`userId\` varchar(255) NOT NULL, \`comment\` text NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`product_reviews\` (\`id\` VARCHAR(36) NOT NULL, \`productId\` varchar(255) NOT NULL, \`userId\` varchar(255) NOT NULL, \`orderId\` varchar(255) NULL, \`rating\` tinyint NOT NULL, \`comment\` text NULL, \`images\` json NULL, \`isVerified\` tinyint NOT NULL DEFAULT 0, \`helpfulCount\` int NOT NULL DEFAULT '0', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_964f13abf796aca25d7e5849c6\` (\`userId\`), INDEX \`IDX_32edd80d91dff1bc19e79c8f16\` (\`productId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`inventory_transactions\` (\`id\` VARCHAR(36) NOT NULL, \`productId\` varchar(255) NOT NULL, \`variantId\` varchar(255) NULL, \`inventoryId\` varchar(255) NOT NULL, \`type\` enum ('in', 'out', 'return', 'adjustment') NOT NULL, \`quantity\` int NOT NULL, \`beforeQuantity\` int NOT NULL, \`afterQuantity\` int NOT NULL, \`reason\` varchar(500) NULL, \`reference\` varchar(255) NULL, \`createdBy\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_f21250669a9728997c6d8f6f5d\` (\`productId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`inventories\` (\`id\` VARCHAR(36) NOT NULL, \`productId\` varchar(255) NOT NULL, \`variantId\` varchar(255) NULL, \`quantity\` int NOT NULL DEFAULT '0', \`reservedQuantity\` int NOT NULL DEFAULT '0', \`lastRestockedAt\` timestamp NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_94a72d847b0d13251be3f7329e\` (\`productId\`, \`variantId\`), UNIQUE INDEX \`REL_13d90d420ac9dff1231d1ca010\` (\`variantId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`products\` (\`id\` VARCHAR(36) NOT NULL, \`name\` varchar(500) NOT NULL, \`slug\` varchar(500) NOT NULL, \`description\` text NULL, \`shortDescription\` varchar(500) NULL, \`categoryId\` varchar(255) NOT NULL, \`brandId\` varchar(255) NULL, \`price\` decimal(15,2) NOT NULL DEFAULT '0.00', \`comparePrice\` decimal(15,2) NULL, \`costPrice\` decimal(15,2) NULL, \`sku\` varchar(100) NOT NULL, \`barcode\` varchar(100) NULL, \`quantity\` int NOT NULL DEFAULT '0', \`weight\` decimal(15,2) NULL, \`dimensions\` json NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`isFeatured\` tinyint NOT NULL DEFAULT 0, \`views\` int NOT NULL DEFAULT '0', \`soldCount\` int NOT NULL DEFAULT '0', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_63fcb3d8806a6efd53dbc67430\` (\`createdAt\`), INDEX \`IDX_75895eeb1903f8a17816dafe0a\` (\`price\`), INDEX \`IDX_ea86d0c514c4ecbb5694cbf57d\` (\`brandId\`), INDEX \`IDX_ff56834e735fa78a15d0cf2192\` (\`categoryId\`), UNIQUE INDEX \`IDX_464f927ae360106b783ed0b410\` (\`slug\`), UNIQUE INDEX \`IDX_c44ac33a05b144dd0d9ddcf932\` (\`sku\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`order_items\` (\`id\` VARCHAR(36) NOT NULL, \`orderId\` varchar(255) NOT NULL, \`productId\` varchar(255) NOT NULL, \`variantId\` varchar(255) NULL, \`productName\` varchar(500) NOT NULL, \`variantName\` varchar(255) NULL, \`sku\` varchar(100) NOT NULL, \`image\` varchar(500) NULL, \`quantity\` int NOT NULL, \`price\` decimal(15,2) NOT NULL, \`subtotal\` decimal(15,2) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_f1d359a55923bb45b057fbdab0\` (\`orderId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`payments\` (\`id\` VARCHAR(36) NOT NULL, \`orderId\` varchar(255) NOT NULL, \`amount\` decimal(15,2) NOT NULL, \`method\` enum ('cod', 'vnpay', 'momo', 'bank_transfer') NOT NULL, \`status\` enum ('pending', 'completed', 'failed', 'refunded') NOT NULL DEFAULT 'pending', \`transactionId\` varchar(255) NULL, \`gatewayResponse\` json NULL, \`paidAt\` timestamp NULL, \`refundedAt\` timestamp NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_af929a5f2a400fdb6913b4967e\` (\`orderId\`), UNIQUE INDEX \`REL_af929a5f2a400fdb6913b4967e\` (\`orderId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`shipping_updates\` (\`id\` VARCHAR(36) NOT NULL, \`shipmentId\` varchar(255) NOT NULL, \`status\` varchar(100) NOT NULL, \`location\` varchar(255) NULL, \`note\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`shipments\` (\`id\` VARCHAR(36) NOT NULL, \`orderId\` varchar(255) NOT NULL, \`trackingNumber\` varchar(255) NULL, \`carrier\` varchar(255) NULL, \`status\` enum ('preparing', 'picked_up', 'in_transit', 'out_for_delivery', 'delivered', 'failed') NOT NULL DEFAULT 'preparing', \`shippedAt\` timestamp NULL, \`estimatedDeliveryAt\` timestamp NULL, \`deliveredAt\` timestamp NULL, \`failedReason\` varchar(500) NULL, \`deliveryImages\` json NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_13ba957bcb616719a0dc3fca82\` (\`orderId\`), UNIQUE INDEX \`REL_13ba957bcb616719a0dc3fca82\` (\`orderId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`order_status_history\` (\`id\` VARCHAR(36) NOT NULL, \`orderId\` varchar(255) NOT NULL, \`status\` enum ('pending', 'confirmed', 'processing', 'shipping', 'delivered', 'cancelled', 'refunded') NOT NULL, \`note\` text NULL, \`changedBy\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`orders\` (\`id\` VARCHAR(36) NOT NULL, \`orderNumber\` varchar(50) NOT NULL, \`userId\` varchar(255) NOT NULL, \`status\` enum ('pending', 'confirmed', 'processing', 'shipping', 'delivered', 'cancelled', 'refunded') NOT NULL DEFAULT 'pending', \`subtotal\` decimal(15,2) NOT NULL, \`shippingFee\` decimal(15,2) NOT NULL DEFAULT '0.00', \`tax\` decimal(15,2) NOT NULL DEFAULT '0.00', \`discount\` decimal(15,2) NOT NULL DEFAULT '0.00', \`total\` decimal(15,2) NOT NULL, \`paymentMethod\` enum ('cod', 'vnpay', 'momo', 'bank_transfer') NOT NULL, \`paymentStatus\` enum ('pending', 'completed', 'failed', 'refunded') NOT NULL DEFAULT 'pending', \`shippingAddressId\` varchar(255) NULL, \`billingAddressId\` varchar(255) NULL, \`customerNote\` text NULL, \`adminNote\` text NULL, \`cancelReason\` varchar(500) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`confirmedAt\` timestamp NULL, \`shippedAt\` timestamp NULL, \`deliveredAt\` timestamp NULL, INDEX \`IDX_1f4b9818a08b822a31493fdee9\` (\`createdAt\`), INDEX \`IDX_775c9f06fc27ae3ff8fb26f2c4\` (\`status\`), INDEX \`IDX_151b79a83ba240b0cb31b2302d\` (\`userId\`), UNIQUE INDEX \`IDX_59b0c3b34ea0fa5562342f2414\` (\`orderNumber\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`notifications\` (\`id\` VARCHAR(36) NOT NULL, \`userId\` varchar(255) NOT NULL, \`type\` enum ('order_update', 'promotion', 'system', 'review_reply', 'low_stock', 'new_message') NOT NULL, \`title\` varchar(255) NOT NULL, \`message\` text NOT NULL, \`data\` json NULL, \`icon\` varchar(255) NULL, \`url\` varchar(500) NULL, \`isRead\` tinyint NOT NULL DEFAULT 0, \`readAt\` timestamp NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_831a5a06f879fb0bebf8965871\` (\`createdAt\`), INDEX \`IDX_5340fc241f57310d243e5ab20b\` (\`userId\`, \`isRead\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`notification_settings\` (\`id\` VARCHAR(36) NOT NULL, \`userId\` varchar(255) NOT NULL, \`emailNotifications\` tinyint NOT NULL DEFAULT 1, \`pushNotifications\` tinyint NOT NULL DEFAULT 1, \`orderUpdates\` tinyint NOT NULL DEFAULT 1, \`promotions\` tinyint NOT NULL DEFAULT 1, \`newMessages\` tinyint NOT NULL DEFAULT 1, \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_5a8ffc3b89343043c9440d631e\` (\`userId\`), UNIQUE INDEX \`REL_5a8ffc3b89343043c9440d631e\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_sessions\` (\`id\` VARCHAR(36) NOT NULL, \`userId\` varchar(255) NOT NULL, \`refreshToken\` text NOT NULL, \`expiresAt\` timestamp NOT NULL, \`userAgent\` varchar(500) NULL, \`ipAddress\` varchar(45) NULL, \`socketId\` varchar(100) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_55fa4db8406ed66bc704432842\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` VARCHAR(36) NOT NULL, \`email\` varchar(255) NOT NULL, \`password\` varchar(255) NOT NULL, \`firstName\` varchar(100) NOT NULL, \`lastName\` varchar(100) NOT NULL, \`phone\` varchar(20) NULL, \`avatar\` varchar(500) NULL, \`role\` enum ('admin', 'staff', 'customer') NOT NULL DEFAULT 'customer', \`isActive\` tinyint NOT NULL DEFAULT 1, \`isOnline\` tinyint NOT NULL DEFAULT 0, \`lastSeenAt\` timestamp NULL, \`emailVerified\` tinyint NOT NULL DEFAULT 0, \`emailVerificationToken\` varchar(255) NULL, \`passwordResetToken\` varchar(255) NULL, \`passwordResetExpires\` timestamp NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), UNIQUE INDEX \`IDX_a000cca60bcf04454e72769949\` (\`phone\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`wishlists\` (\`id\` VARCHAR(36) NOT NULL, \`userId\` varchar(255) NOT NULL, \`productId\` varchar(255) NOT NULL, \`variantId\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_4f3c30555daa6ab0b70a1db772\` (\`userId\`), UNIQUE INDEX \`IDX_bf157dc445d8a177b11a0e592a\` (\`userId\`, \`productId\`, \`variantId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`shipping_methods\` (\`id\` VARCHAR(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`baseCost\` decimal(15,2) NOT NULL, \`costPerKm\` decimal(15,2) NULL, \`estimatedDays\` int NOT NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`provinces\` json NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`settings\` (\`id\` VARCHAR(36) NOT NULL, \`key\` varchar(255) NOT NULL, \`value\` json NOT NULL, \`category\` varchar(100) NULL, \`description\` text NULL, \`updatedBy\` varchar(255) NULL, \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_c8639b7626fa94ba8265628f21\` (\`key\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`search_logs\` (\`id\` VARCHAR(36) NOT NULL, \`query\` varchar(500) NOT NULL, \`userId\` varchar(255) NULL, \`sessionId\` varchar(255) NULL, \`resultsCount\` int NOT NULL DEFAULT '0', \`clickedProductId\` varchar(255) NULL, \`searchedAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX \`IDX_e5fcda742fd691ffeecc90cdea\` (\`searchedAt\`), INDEX \`IDX_b9ed845f64d320e335caee62d3\` (\`query\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`product_views\` (\`id\` VARCHAR(36) NOT NULL, \`productId\` varchar(255) NOT NULL, \`userId\` varchar(255) NULL, \`sessionId\` varchar(255) NULL, \`ipAddress\` varchar(45) NULL, \`userAgent\` varchar(500) NULL, \`viewedAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX \`IDX_cd3171dd75c208cefe0c510775\` (\`viewedAt\`), INDEX \`IDX_0eeddd2967d61998a9fb6bc3be\` (\`productId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`conversation_participants\` (\`id\` VARCHAR(36) NOT NULL, \`conversationId\` varchar(255) NOT NULL, \`userId\` varchar(255) NOT NULL, \`role\` enum ('customer', 'admin', 'staff') NOT NULL, \`joinedAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, \`lastReadAt\` timestamp NULL, UNIQUE INDEX \`IDX_e43efbfa3b850160b5b2c50e3e\` (\`conversationId\`, \`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`conversations\` (\`id\` VARCHAR(36) NOT NULL, \`type\` enum ('customer_support', 'order_inquiry') NOT NULL, \`orderId\` varchar(255) NULL, \`status\` enum ('open', 'closed') NOT NULL DEFAULT 'open', \`lastMessageAt\` timestamp NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`messages\` (\`id\` VARCHAR(36) NOT NULL, \`conversationId\` varchar(255) NOT NULL, \`senderId\` varchar(255) NOT NULL, \`message\` text NOT NULL, \`attachments\` json NULL, \`type\` enum ('text', 'image', 'file', 'system') NOT NULL DEFAULT 'text', \`isEdited\` tinyint NOT NULL DEFAULT 0, \`isDeleted\` tinyint NOT NULL DEFAULT 0, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_751332fc6cc6fc576c6975cd07\` (\`conversationId\`, \`createdAt\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`message_read_receipts\` (\`id\` VARCHAR(36) NOT NULL, \`messageId\` varchar(255) NOT NULL, \`userId\` varchar(255) NOT NULL, \`readAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE INDEX \`IDX_14760574686d908c45d6d01e66\` (\`messageId\`, \`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`coupon_usages\` (\`id\` VARCHAR(36) NOT NULL, \`couponId\` varchar(255) NOT NULL, \`userId\` varchar(255) NOT NULL, \`orderId\` varchar(255) NOT NULL, \`usedAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`coupons\` (\`id\` VARCHAR(36) NOT NULL, \`code\` varchar(50) NOT NULL, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`type\` enum ('percentage', 'fixed_amount', 'free_shipping') NOT NULL, \`value\` decimal(15,2) NOT NULL, \`minOrderValue\` decimal(15,2) NOT NULL DEFAULT '0.00', \`maxDiscount\` decimal(15,2) NULL, \`usageLimit\` int NULL, \`usedCount\` int NOT NULL DEFAULT '0', \`userUsageLimit\` int NOT NULL DEFAULT '1', \`startDate\` timestamp NOT NULL, \`endDate\` timestamp NOT NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`applicableProducts\` json NULL, \`applicableCategories\` json NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_2f6534b9cdfddd56603ed4d0e6\` (\`startDate\`, \`endDate\`), INDEX \`IDX_3650fd30e88e27baa3a88e1e9f\` (\`isActive\`), UNIQUE INDEX \`IDX_e025109230e82925843f2a14c4\` (\`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`flash_sale_items\` (\`id\` VARCHAR(36) NOT NULL, \`flashSaleId\` varchar(255) NOT NULL, \`productId\` varchar(255) NOT NULL, \`variantId\` varchar(255) NULL, \`discountPercent\` decimal(5,2) NOT NULL, \`originalPrice\` decimal(15,2) NOT NULL, \`salePrice\` decimal(15,2) NOT NULL, \`quantity\` int NOT NULL, \`soldQuantity\` int NOT NULL DEFAULT '0', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`flash_sales\` (\`id\` VARCHAR(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`startDate\` timestamp NOT NULL, \`endDate\` timestamp NOT NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`banners\` (\`id\` VARCHAR(36) NOT NULL, \`title\` varchar(255) NOT NULL, \`image\` varchar(500) NOT NULL, \`link\` varchar(500) NULL, \`displayOrder\` int NOT NULL DEFAULT '0', \`startDate\` timestamp NULL, \`endDate\` timestamp NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`placement\` enum ('home', 'category', 'product') NOT NULL DEFAULT 'home', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`addresses\` ADD CONSTRAINT \`FK_95c93a584de49f0b0e13f753630\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD CONSTRAINT \`FK_9a6f051e66982b5f0318981bcaa\` FOREIGN KEY (\`parentId\`) REFERENCES \`categories\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_images\` ADD CONSTRAINT \`FK_b367708bf720c8dd62fc6833161\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`carts\` ADD CONSTRAINT \`FK_69828a178f152f157dcf2f70a89\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD CONSTRAINT \`FK_edd714311619a5ad09525045838\` FOREIGN KEY (\`cartId\`) REFERENCES \`carts\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD CONSTRAINT \`FK_72679d98b31c737937b8932ebe6\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD CONSTRAINT \`FK_5a27845bc2d79be6f1fa3d2c036\` FOREIGN KEY (\`variantId\`) REFERENCES \`product_variants\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_variants\` ADD CONSTRAINT \`FK_f515690c571a03400a9876600b5\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`review_replies\` ADD CONSTRAINT \`FK_385273ae9fd7dc7313e9933cf57\` FOREIGN KEY (\`reviewId\`) REFERENCES \`product_reviews\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`review_replies\` ADD CONSTRAINT \`FK_37e9e13a85e6a9ac6fcf778ee6b\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_reviews\` ADD CONSTRAINT \`FK_32edd80d91dff1bc19e79c8f16d\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_reviews\` ADD CONSTRAINT \`FK_964f13abf796aca25d7e5849c64\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_reviews\` ADD CONSTRAINT \`FK_f1432cc7dde8c52ac11151d439e\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`inventory_transactions\` ADD CONSTRAINT \`FK_f21250669a9728997c6d8f6f5da\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`inventory_transactions\` ADD CONSTRAINT \`FK_53aa9ed764e39ed8283aed23770\` FOREIGN KEY (\`variantId\`) REFERENCES \`product_variants\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`inventory_transactions\` ADD CONSTRAINT \`FK_f306c4cf8c2a4cd3d5653ba974e\` FOREIGN KEY (\`inventoryId\`) REFERENCES \`inventories\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`inventory_transactions\` ADD CONSTRAINT \`FK_8927d776cb7bd98e563a51b2a26\` FOREIGN KEY (\`createdBy\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`inventories\` ADD CONSTRAINT \`FK_19f6e91bd3b53e47103305f3f84\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`inventories\` ADD CONSTRAINT \`FK_13d90d420ac9dff1231d1ca0100\` FOREIGN KEY (\`variantId\`) REFERENCES \`product_variants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_ff56834e735fa78a15d0cf21926\` FOREIGN KEY (\`categoryId\`) REFERENCES \`categories\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_ea86d0c514c4ecbb5694cbf57df\` FOREIGN KEY (\`brandId\`) REFERENCES \`brands\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_f1d359a55923bb45b057fbdab0d\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_cdb99c05982d5191ac8465ac010\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_516736b9807228bb17b2d0a3e2a\` FOREIGN KEY (\`variantId\`) REFERENCES \`product_variants\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD CONSTRAINT \`FK_af929a5f2a400fdb6913b4967e1\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shipping_updates\` ADD CONSTRAINT \`FK_39452a02e71465db95c35427976\` FOREIGN KEY (\`shipmentId\`) REFERENCES \`shipments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shipments\` ADD CONSTRAINT \`FK_13ba957bcb616719a0dc3fca82f\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_status_history\` ADD CONSTRAINT \`FK_689db3835e5550e68d26ca32676\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_status_history\` ADD CONSTRAINT \`FK_e8c23988e2e618bbff2b4b43a59\` FOREIGN KEY (\`changedBy\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_151b79a83ba240b0cb31b2302d1\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_cc4e4adab232e8c05026b2f345d\` FOREIGN KEY (\`shippingAddressId\`) REFERENCES \`addresses\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_820a4c09ddad44884a97378d336\` FOREIGN KEY (\`billingAddressId\`) REFERENCES \`addresses\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_692a909ee0fa9383e7859f9b406\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notification_settings\` ADD CONSTRAINT \`FK_5a8ffc3b89343043c9440d631e2\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_sessions\` ADD CONSTRAINT \`FK_55fa4db8406ed66bc7044328427\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`wishlists\` ADD CONSTRAINT \`FK_4f3c30555daa6ab0b70a1db772c\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`wishlists\` ADD CONSTRAINT \`FK_063c6f46d6cbebf35f3a5ec3d4e\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`wishlists\` ADD CONSTRAINT \`FK_48f0ade12ecf1ffe69005c13f6a\` FOREIGN KEY (\`variantId\`) REFERENCES \`product_variants\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`settings\` ADD CONSTRAINT \`FK_e081a6cf2fa857fbbef9c3d5554\` FOREIGN KEY (\`updatedBy\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`search_logs\` ADD CONSTRAINT \`FK_8c823ac135c1cdfe48a79854fa3\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`search_logs\` ADD CONSTRAINT \`FK_d9a61ac0d4491930bfab4147df0\` FOREIGN KEY (\`clickedProductId\`) REFERENCES \`products\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_views\` ADD CONSTRAINT \`FK_0eeddd2967d61998a9fb6bc3be0\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_views\` ADD CONSTRAINT \`FK_28453e231373168ec22f863956b\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conversation_participants\` ADD CONSTRAINT \`FK_4453e20858b14ab765a09ad728c\` FOREIGN KEY (\`conversationId\`) REFERENCES \`conversations\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conversation_participants\` ADD CONSTRAINT \`FK_18c4ba3b127461649e5f5039dbf\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conversations\` ADD CONSTRAINT \`FK_1fc3133b966bb83dc957188b712\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`FK_e5663ce0c730b2de83445e2fd19\` FOREIGN KEY (\`conversationId\`) REFERENCES \`conversations\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`FK_2db9cf2b3ca111742793f6c37ce\` FOREIGN KEY (\`senderId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`message_read_receipts\` ADD CONSTRAINT \`FK_7b27375e3d32b327050103cf6df\` FOREIGN KEY (\`messageId\`) REFERENCES \`messages\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`message_read_receipts\` ADD CONSTRAINT \`FK_1623e4199eb5e0d7296a8b70014\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`coupon_usages\` ADD CONSTRAINT \`FK_a7b422cc0dbf863671255eaad57\` FOREIGN KEY (\`couponId\`) REFERENCES \`coupons\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`coupon_usages\` ADD CONSTRAINT \`FK_f526503f2419217d16794648f29\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`coupon_usages\` ADD CONSTRAINT \`FK_131640403c2fdd7a65ab7218873\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`flash_sale_items\` ADD CONSTRAINT \`FK_22e50748cc477cdda44501c2b7c\` FOREIGN KEY (\`flashSaleId\`) REFERENCES \`flash_sales\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`flash_sale_items\` ADD CONSTRAINT \`FK_03805a77952333cce8489919bc1\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`flash_sale_items\` ADD CONSTRAINT \`FK_85233af8512d463ac2b8ae7619a\` FOREIGN KEY (\`variantId\`) REFERENCES \`product_variants\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`flash_sale_items\` DROP FOREIGN KEY \`FK_85233af8512d463ac2b8ae7619a\``);
        await queryRunner.query(`ALTER TABLE \`flash_sale_items\` DROP FOREIGN KEY \`FK_03805a77952333cce8489919bc1\``);
        await queryRunner.query(`ALTER TABLE \`flash_sale_items\` DROP FOREIGN KEY \`FK_22e50748cc477cdda44501c2b7c\``);
        await queryRunner.query(`ALTER TABLE \`coupon_usages\` DROP FOREIGN KEY \`FK_131640403c2fdd7a65ab7218873\``);
        await queryRunner.query(`ALTER TABLE \`coupon_usages\` DROP FOREIGN KEY \`FK_f526503f2419217d16794648f29\``);
        await queryRunner.query(`ALTER TABLE \`coupon_usages\` DROP FOREIGN KEY \`FK_a7b422cc0dbf863671255eaad57\``);
        await queryRunner.query(`ALTER TABLE \`message_read_receipts\` DROP FOREIGN KEY \`FK_1623e4199eb5e0d7296a8b70014\``);
        await queryRunner.query(`ALTER TABLE \`message_read_receipts\` DROP FOREIGN KEY \`FK_7b27375e3d32b327050103cf6df\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`FK_2db9cf2b3ca111742793f6c37ce\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`FK_e5663ce0c730b2de83445e2fd19\``);
        await queryRunner.query(`ALTER TABLE \`conversations\` DROP FOREIGN KEY \`FK_1fc3133b966bb83dc957188b712\``);
        await queryRunner.query(`ALTER TABLE \`conversation_participants\` DROP FOREIGN KEY \`FK_18c4ba3b127461649e5f5039dbf\``);
        await queryRunner.query(`ALTER TABLE \`conversation_participants\` DROP FOREIGN KEY \`FK_4453e20858b14ab765a09ad728c\``);
        await queryRunner.query(`ALTER TABLE \`product_views\` DROP FOREIGN KEY \`FK_28453e231373168ec22f863956b\``);
        await queryRunner.query(`ALTER TABLE \`product_views\` DROP FOREIGN KEY \`FK_0eeddd2967d61998a9fb6bc3be0\``);
        await queryRunner.query(`ALTER TABLE \`search_logs\` DROP FOREIGN KEY \`FK_d9a61ac0d4491930bfab4147df0\``);
        await queryRunner.query(`ALTER TABLE \`search_logs\` DROP FOREIGN KEY \`FK_8c823ac135c1cdfe48a79854fa3\``);
        await queryRunner.query(`ALTER TABLE \`settings\` DROP FOREIGN KEY \`FK_e081a6cf2fa857fbbef9c3d5554\``);
        await queryRunner.query(`ALTER TABLE \`wishlists\` DROP FOREIGN KEY \`FK_48f0ade12ecf1ffe69005c13f6a\``);
        await queryRunner.query(`ALTER TABLE \`wishlists\` DROP FOREIGN KEY \`FK_063c6f46d6cbebf35f3a5ec3d4e\``);
        await queryRunner.query(`ALTER TABLE \`wishlists\` DROP FOREIGN KEY \`FK_4f3c30555daa6ab0b70a1db772c\``);
        await queryRunner.query(`ALTER TABLE \`user_sessions\` DROP FOREIGN KEY \`FK_55fa4db8406ed66bc7044328427\``);
        await queryRunner.query(`ALTER TABLE \`notification_settings\` DROP FOREIGN KEY \`FK_5a8ffc3b89343043c9440d631e2\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_692a909ee0fa9383e7859f9b406\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_820a4c09ddad44884a97378d336\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_cc4e4adab232e8c05026b2f345d\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_151b79a83ba240b0cb31b2302d1\``);
        await queryRunner.query(`ALTER TABLE \`order_status_history\` DROP FOREIGN KEY \`FK_e8c23988e2e618bbff2b4b43a59\``);
        await queryRunner.query(`ALTER TABLE \`order_status_history\` DROP FOREIGN KEY \`FK_689db3835e5550e68d26ca32676\``);
        await queryRunner.query(`ALTER TABLE \`shipments\` DROP FOREIGN KEY \`FK_13ba957bcb616719a0dc3fca82f\``);
        await queryRunner.query(`ALTER TABLE \`shipping_updates\` DROP FOREIGN KEY \`FK_39452a02e71465db95c35427976\``);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP FOREIGN KEY \`FK_af929a5f2a400fdb6913b4967e1\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_516736b9807228bb17b2d0a3e2a\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_cdb99c05982d5191ac8465ac010\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_f1d359a55923bb45b057fbdab0d\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_ea86d0c514c4ecbb5694cbf57df\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_ff56834e735fa78a15d0cf21926\``);
        await queryRunner.query(`ALTER TABLE \`inventories\` DROP FOREIGN KEY \`FK_13d90d420ac9dff1231d1ca0100\``);
        await queryRunner.query(`ALTER TABLE \`inventories\` DROP FOREIGN KEY \`FK_19f6e91bd3b53e47103305f3f84\``);
        await queryRunner.query(`ALTER TABLE \`inventory_transactions\` DROP FOREIGN KEY \`FK_8927d776cb7bd98e563a51b2a26\``);
        await queryRunner.query(`ALTER TABLE \`inventory_transactions\` DROP FOREIGN KEY \`FK_f306c4cf8c2a4cd3d5653ba974e\``);
        await queryRunner.query(`ALTER TABLE \`inventory_transactions\` DROP FOREIGN KEY \`FK_53aa9ed764e39ed8283aed23770\``);
        await queryRunner.query(`ALTER TABLE \`inventory_transactions\` DROP FOREIGN KEY \`FK_f21250669a9728997c6d8f6f5da\``);
        await queryRunner.query(`ALTER TABLE \`product_reviews\` DROP FOREIGN KEY \`FK_f1432cc7dde8c52ac11151d439e\``);
        await queryRunner.query(`ALTER TABLE \`product_reviews\` DROP FOREIGN KEY \`FK_964f13abf796aca25d7e5849c64\``);
        await queryRunner.query(`ALTER TABLE \`product_reviews\` DROP FOREIGN KEY \`FK_32edd80d91dff1bc19e79c8f16d\``);
        await queryRunner.query(`ALTER TABLE \`review_replies\` DROP FOREIGN KEY \`FK_37e9e13a85e6a9ac6fcf778ee6b\``);
        await queryRunner.query(`ALTER TABLE \`review_replies\` DROP FOREIGN KEY \`FK_385273ae9fd7dc7313e9933cf57\``);
        await queryRunner.query(`ALTER TABLE \`product_variants\` DROP FOREIGN KEY \`FK_f515690c571a03400a9876600b5\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP FOREIGN KEY \`FK_5a27845bc2d79be6f1fa3d2c036\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP FOREIGN KEY \`FK_72679d98b31c737937b8932ebe6\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP FOREIGN KEY \`FK_edd714311619a5ad09525045838\``);
        await queryRunner.query(`ALTER TABLE \`carts\` DROP FOREIGN KEY \`FK_69828a178f152f157dcf2f70a89\``);
        await queryRunner.query(`ALTER TABLE \`product_images\` DROP FOREIGN KEY \`FK_b367708bf720c8dd62fc6833161\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP FOREIGN KEY \`FK_9a6f051e66982b5f0318981bcaa\``);
        await queryRunner.query(`ALTER TABLE \`addresses\` DROP FOREIGN KEY \`FK_95c93a584de49f0b0e13f753630\``);
        await queryRunner.query(`DROP TABLE \`banners\``);
        await queryRunner.query(`DROP TABLE \`flash_sales\``);
        await queryRunner.query(`DROP TABLE \`flash_sale_items\``);
        await queryRunner.query(`DROP INDEX \`IDX_e025109230e82925843f2a14c4\` ON \`coupons\``);
        await queryRunner.query(`DROP INDEX \`IDX_3650fd30e88e27baa3a88e1e9f\` ON \`coupons\``);
        await queryRunner.query(`DROP INDEX \`IDX_2f6534b9cdfddd56603ed4d0e6\` ON \`coupons\``);
        await queryRunner.query(`DROP TABLE \`coupons\``);
        await queryRunner.query(`DROP TABLE \`coupon_usages\``);
        await queryRunner.query(`DROP INDEX \`IDX_14760574686d908c45d6d01e66\` ON \`message_read_receipts\``);
        await queryRunner.query(`DROP TABLE \`message_read_receipts\``);
        await queryRunner.query(`DROP INDEX \`IDX_751332fc6cc6fc576c6975cd07\` ON \`messages\``);
        await queryRunner.query(`DROP TABLE \`messages\``);
        await queryRunner.query(`DROP TABLE \`conversations\``);
        await queryRunner.query(`DROP INDEX \`IDX_e43efbfa3b850160b5b2c50e3e\` ON \`conversation_participants\``);
        await queryRunner.query(`DROP TABLE \`conversation_participants\``);
        await queryRunner.query(`DROP INDEX \`IDX_0eeddd2967d61998a9fb6bc3be\` ON \`product_views\``);
        await queryRunner.query(`DROP INDEX \`IDX_cd3171dd75c208cefe0c510775\` ON \`product_views\``);
        await queryRunner.query(`DROP TABLE \`product_views\``);
        await queryRunner.query(`DROP INDEX \`IDX_b9ed845f64d320e335caee62d3\` ON \`search_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_e5fcda742fd691ffeecc90cdea\` ON \`search_logs\``);
        await queryRunner.query(`DROP TABLE \`search_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_c8639b7626fa94ba8265628f21\` ON \`settings\``);
        await queryRunner.query(`DROP TABLE \`settings\``);
        await queryRunner.query(`DROP TABLE \`shipping_methods\``);
        await queryRunner.query(`DROP INDEX \`IDX_bf157dc445d8a177b11a0e592a\` ON \`wishlists\``);
        await queryRunner.query(`DROP INDEX \`IDX_4f3c30555daa6ab0b70a1db772\` ON \`wishlists\``);
        await queryRunner.query(`DROP TABLE \`wishlists\``);
        await queryRunner.query(`DROP INDEX \`IDX_a000cca60bcf04454e72769949\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_55fa4db8406ed66bc704432842\` ON \`user_sessions\``);
        await queryRunner.query(`DROP TABLE \`user_sessions\``);
        await queryRunner.query(`DROP INDEX \`REL_5a8ffc3b89343043c9440d631e\` ON \`notification_settings\``);
        await queryRunner.query(`DROP INDEX \`IDX_5a8ffc3b89343043c9440d631e\` ON \`notification_settings\``);
        await queryRunner.query(`DROP TABLE \`notification_settings\``);
        await queryRunner.query(`DROP INDEX \`IDX_5340fc241f57310d243e5ab20b\` ON \`notifications\``);
        await queryRunner.query(`DROP INDEX \`IDX_831a5a06f879fb0bebf8965871\` ON \`notifications\``);
        await queryRunner.query(`DROP TABLE \`notifications\``);
        await queryRunner.query(`DROP INDEX \`IDX_59b0c3b34ea0fa5562342f2414\` ON \`orders\``);
        await queryRunner.query(`DROP INDEX \`IDX_151b79a83ba240b0cb31b2302d\` ON \`orders\``);
        await queryRunner.query(`DROP INDEX \`IDX_775c9f06fc27ae3ff8fb26f2c4\` ON \`orders\``);
        await queryRunner.query(`DROP INDEX \`IDX_1f4b9818a08b822a31493fdee9\` ON \`orders\``);
        await queryRunner.query(`DROP TABLE \`orders\``);
        await queryRunner.query(`DROP TABLE \`order_status_history\``);
        await queryRunner.query(`DROP INDEX \`REL_13ba957bcb616719a0dc3fca82\` ON \`shipments\``);
        await queryRunner.query(`DROP INDEX \`IDX_13ba957bcb616719a0dc3fca82\` ON \`shipments\``);
        await queryRunner.query(`DROP TABLE \`shipments\``);
        await queryRunner.query(`DROP TABLE \`shipping_updates\``);
        await queryRunner.query(`DROP INDEX \`REL_af929a5f2a400fdb6913b4967e\` ON \`payments\``);
        await queryRunner.query(`DROP INDEX \`IDX_af929a5f2a400fdb6913b4967e\` ON \`payments\``);
        await queryRunner.query(`DROP TABLE \`payments\``);
        await queryRunner.query(`DROP INDEX \`IDX_f1d359a55923bb45b057fbdab0\` ON \`order_items\``);
        await queryRunner.query(`DROP TABLE \`order_items\``);
        await queryRunner.query(`DROP INDEX \`IDX_c44ac33a05b144dd0d9ddcf932\` ON \`products\``);
        await queryRunner.query(`DROP INDEX \`IDX_464f927ae360106b783ed0b410\` ON \`products\``);
        await queryRunner.query(`DROP INDEX \`IDX_ff56834e735fa78a15d0cf2192\` ON \`products\``);
        await queryRunner.query(`DROP INDEX \`IDX_ea86d0c514c4ecbb5694cbf57d\` ON \`products\``);
        await queryRunner.query(`DROP INDEX \`IDX_75895eeb1903f8a17816dafe0a\` ON \`products\``);
        await queryRunner.query(`DROP INDEX \`IDX_63fcb3d8806a6efd53dbc67430\` ON \`products\``);
        await queryRunner.query(`DROP TABLE \`products\``);
        await queryRunner.query(`DROP INDEX \`REL_13d90d420ac9dff1231d1ca010\` ON \`inventories\``);
        await queryRunner.query(`DROP INDEX \`IDX_94a72d847b0d13251be3f7329e\` ON \`inventories\``);
        await queryRunner.query(`DROP TABLE \`inventories\``);
        await queryRunner.query(`DROP INDEX \`IDX_f21250669a9728997c6d8f6f5d\` ON \`inventory_transactions\``);
        await queryRunner.query(`DROP TABLE \`inventory_transactions\``);
        await queryRunner.query(`DROP INDEX \`IDX_32edd80d91dff1bc19e79c8f16\` ON \`product_reviews\``);
        await queryRunner.query(`DROP INDEX \`IDX_964f13abf796aca25d7e5849c6\` ON \`product_reviews\``);
        await queryRunner.query(`DROP TABLE \`product_reviews\``);
        await queryRunner.query(`DROP TABLE \`review_replies\``);
        await queryRunner.query(`DROP INDEX \`IDX_46f236f21640f9da218a063a86\` ON \`product_variants\``);
        await queryRunner.query(`DROP INDEX \`IDX_f515690c571a03400a9876600b\` ON \`product_variants\``);
        await queryRunner.query(`DROP TABLE \`product_variants\``);
        await queryRunner.query(`DROP INDEX \`IDX_edd714311619a5ad0952504583\` ON \`cart_items\``);
        await queryRunner.query(`DROP TABLE \`cart_items\``);
        await queryRunner.query(`DROP INDEX \`REL_69828a178f152f157dcf2f70a8\` ON \`carts\``);
        await queryRunner.query(`DROP INDEX \`IDX_08c5fb75dc0c2ed434aac2b0f5\` ON \`carts\``);
        await queryRunner.query(`DROP INDEX \`IDX_69828a178f152f157dcf2f70a8\` ON \`carts\``);
        await queryRunner.query(`DROP TABLE \`carts\``);
        await queryRunner.query(`DROP INDEX \`IDX_b367708bf720c8dd62fc683316\` ON \`product_images\``);
        await queryRunner.query(`DROP TABLE \`product_images\``);
        await queryRunner.query(`DROP INDEX \`IDX_b15428f362be2200922952dc26\` ON \`brands\``);
        await queryRunner.query(`DROP TABLE \`brands\``);
        await queryRunner.query(`DROP INDEX \`IDX_420d9f679d41281f282f5bc7d0\` ON \`categories\``);
        await queryRunner.query(`DROP TABLE \`categories\``);
        await queryRunner.query(`DROP INDEX \`IDX_95c93a584de49f0b0e13f75363\` ON \`addresses\``);
        await queryRunner.query(`DROP TABLE \`addresses\``);
    }

}
